Update patch set 4
Patch Set 4: Verified-1

[2018-11-15 11:33:31,945] [main] WARN  com.google.gerrit.server.plugins.PluginLoader : Cannot load plugin task-2.16
com.google.gerrit.server.plugins.InvalidPluginException: Unable to load plugin Guice Modules
        at com.google.gerrit.server.plugins.ServerPlugin.loadGuiceModules(ServerPlugin.java:109)
        at com.google.gerrit.server.plugins.ServerPlugin.<init>(ServerPlugin.java:85)
        at com.google.gerrit.server.plugins.JarPluginProvider.loadJarPlugin(JarPluginProvider.java:156)
        at com.google.gerrit.server.plugins.JarPluginProvider.get(JarPluginProvider.java:85)
        at com.google.gerrit.server.plugins.UniversalServerPluginProvider.get(UniversalServerPluginProvider.java:41)
        at com.google.gerrit.server.plugins.PluginLoader.loadServerPlugin(PluginLoader.java:610)
        at com.google.gerrit.server.plugins.PluginLoader.loadPlugin(PluginLoader.java:580)
        at com.google.gerrit.server.plugins.PluginLoader.runPlugin(PluginLoader.java:479)
        at com.google.gerrit.server.plugins.PluginLoader.rescan(PluginLoader.java:423)
        at com.google.gerrit.server.plugins.PluginLoader.start(PluginLoader.java:328)
        at com.google.gerrit.lifecycle.LifecycleManager.start(LifecycleManager.java:95)
        at com.google.gerrit.pgm.Daemon.start(Daemon.java:358)
        at com.google.gerrit.pgm.Daemon.run(Daemon.java:267)
        at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.gerrit.launcher.GerritLauncher.invokeProgram(GerritLauncher.java:226)
        at com.google.gerrit.launcher.GerritLauncher.mainImpl(GerritLauncher.java:122)
        at com.google.gerrit.launcher.GerritLauncher.main(GerritLauncher.java:66)
        at Main.main(Main.java:28)
Caused by: java.lang.ClassNotFoundException: com.googlesource.gerrit.plugins.task.Modules$Module
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at com.google.gerrit.server.plugins.ServerPlugin.load(ServerPlugin.java:120)
        at com.google.gerrit.server.plugins.ServerPlugin.loadGuiceModules(ServerPlugin.java:105)
        ... 21 more

Patch-set: 4
Reviewer: Gerrit User 1002666 <1002666@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1