Fix '--task--include-statistics' option
Currently, on passing the option tasks plugin fails to add the
attributes with error [1] and output [2].

[1] error populating attribute on changes from plugin task [CONTEXT ratelimit_period="1 MINUTES" request="SSH" ]
java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Lcom.googlesource.gerrit.plugins.task.util.TopKeyMap$Entry; ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; [Lcom.googlesource.gerrit.plugins.task.util.TopKeyMap$Entry; is in unnamed module of loader java.net.FactoryURLClassLoader @58961770)
        at com.googlesource.gerrit.plugins.task.util.TopKeyMap.<init>(TopKeyMap.java:66)
        at com.googlesource.gerrit.plugins.task.statistics.HitHashMap.initStatistics(HitHashMap.java:144)
        at com.googlesource.gerrit.plugins.task.PredicateCache.initStatistics(PredicateCache.java:59)
        at com.googlesource.gerrit.plugins.task.TaskPluginDefinedInfoFactory.initStatistics(TaskPluginDefinedInfoFactory.java:405)
        at com.googlesource.gerrit.plugins.task.TaskPluginDefinedInfoFactory.createPluginDefinedInfos(TaskPluginDefinedInfoFactory.java:138)

[2] "message": "Something went wrong in plugin: task"

Impact: '--task--include-statistics' works as expected
Risk-Scope: '--task--include-statistics' option
Change-Id: Id76ea65909a93afaffd3747afef1ac41a7ae3aeb